### ISSUE TITLE
Task 'Terraform Installer' version 2 (TerraformInstaller@2) is dependent on a Node version (10) that is end-of-life

### ISSUE THREAD

**Issue by DominikKrissVisma** [charleszipp/azure-pipelines-tasks-terraform#452] opened 2024-11-20 18:00 UTC
**Describe the bug**
While running tasks (both installer and CLI) in ADO pipeline, we got node related warning:

```
##[warning]Task 'Terraform Installer' version 2 (TerraformInstaller@2) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
##[warning]Task 'Terraform CLI' version 2 (TerraformCLI@2) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```
same bahavior is applicable when using TerraformCLI@1 and TerraformInstaller@1

**To Reproduce**
1. Run TerraformInstaller@2 or TerraformCLI@2 tasks in ADO pipeline 

**Expected behavior**
there should not be any Node warning

**Agent Configuration**
 - OS: linux/windows
 - linux selfhosted, Microsoft Windows Server 2022 azure hosted

**Comment by jason-johnson** [comment] 2024-11-23 07:40
Duplicate of #447

**Closed as completed by jason-johnson** 2024-11-23 07:40 UTC
Labels: bug
