### ISSUE TITLE
##[error]Terraform command 'plan' failed with exit code '0. (task version 0.4.12)

### ISSUE THREAD

**Issue by saiprasanthrajavarapu** [charleszipp/azure-pipelines-tasks-terraform#77] opened 2019-08-07 21:04 UTC
Terraform Plan command gives plan and fails with `##[error]Terraform command 'plan' failed with exit code '0.`  

Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.4.12
Author       : Charles Zipp

**Comment by charleszipp** [comment] 2019-08-07 21:12
@saiprasanthrajavarapu can you please repro with debug enabled and attach the log file from the azure devops task here?

**Comment by saiprasanthrajavarapu** [comment] 2019-08-07 21:21
Please find logs attached 
[tasklog_9.log](https://github.com/charleszipp/azure-pipelines-tasks-terraform/files/3478951/tasklog_9.log)

**Comment by nachogrj** [comment] 2019-08-08 09:55
I have been getting the same error since the las task version was released (0.4.12) but when executing the **init** command. The exception doesn't show a list of errors [as it should](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/4274dcc35da7d8cbef3ac30aab3992bbfdc7d21f/TerraformCLI/src/terraform-aggregate-error.ts#L23), so it means it there are no errors in the [stderr](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/4274dcc35da7d8cbef3ac30aab3992bbfdc7d21f/TerraformCLI/src/terraform-runner.ts#L138). In my case it sets TERRAFORM_LAST_EXITCODE=1 but shows the '0' exit code, I think these might be the reasons. I don't know why the stderr is void or why it even launches an exception but the error tracking has brought me to that.

**Comment by charleszipp** [comment] 2019-08-08 13:46
thanks for the additional context and logs @saiprasanthrajavarapu and @nachogrj. I'm flagging this as a defect for now. My suspicion is that these errors are not writing to stderr (as @nachogrj indicated). It may be solved by examining both stderr & exit code to figure out of the command failed.

**Comment by scott1138** [comment] 2019-08-08 17:52
@charleszipp what does "flagging this as a defect" mean for the task?  Are you rolling back the changes?

**Comment by charleszipp** [comment] 2019-08-08 18:09
@scott1138 it just simply means that the task isnt working as designed. I do not typically "rollback" changes to fix a defect. I typically release new version with a fix. If you @nachogrj and @saiprasanthrajavarapu can provide some context around severity, that will help me prioritize this against other work. Is this blocking deployments? Have you found a workaround? Please identify any extra steps (manual or automated) that you have had to introduce as a result of this issue.

**Comment by saiprasanthrajavarapu** [comment] 2019-08-08 19:32
@charleszipp  we have a workaround for now, we are leveraging "continue on error" option, but the sooner the fix it will be easy for us to get status of the task

**Comment by charleszipp** [comment] 2019-08-08 20:22
Thanks @saiprasanthrajavarapu . I am looking into the issue now. It looks like what may be happening is that the terraform provider is writing to stderr even when the exit code is 0 (i.e. was successful). This task incorrectly assumes that stderr having content = failure. If true this should be as simple as switching one line from examining stderr to examining the exit code. I am working on writing up automated test to verify my theory. I will aim to have fix released by EOD tomorrow.

cc @scott1138 @nachogrj

**Comment by nachogrj** [comment] 2019-08-09 07:05
@charleszipp This issue is blocking our deployments because we don't find any workaround. It throws the error in the "terraform version" command that is executed before every task. 
Thanks to @sergiomcalzada for helping me to review this issue

**Comment by nachogrj** [comment] 2019-08-09 07:30
We have found a workaround to avoid the issue, by disabling the terraform log debugging variable TF_LOG. If it is set, [it writes the errors on the stderr](https://www.terraform.io/docs/internals/debugging.html), even when it has no errors apparently.

**Comment by charleszipp** [comment] 2019-08-09 12:45
Thanks for adding the info @nachogrj! The change i made for this should allow the task to succeed despite having the debug logging writing to stderr so long as the exit code is a successful one.

@saiprasanthrajavarapu @scott1138 see workaround posted by @nachogrj . I should however have a fix out today.

**Comment by charleszipp** [comment] 2019-08-09 14:58
@nachogrj @saiprasanthrajavarapu @scott1138 this was released this morning with 0.4.13. Please let me know if the updated version resolves this issue. If i dont hear back by weds next week i will assume this resolved your issue and close this.

**Comment by saiprasanthrajavarapu** [comment] 2019-08-09 17:55
@charleszipp atleast I am not seeing this issue anymore after upgrading to 0.4.13.

**Comment by nachogrj** [comment] 2019-08-12 06:56
@charleszipp It's working ok for me too, thanks for solving it

**Comment by charleszipp** [comment] 2019-08-12 13:17
released with 0.4.13. Closing as confirmed to have solved issue by both @saiprasanthrajavarapu and @nachogrj

**Closed** 2019-08-12 13:17 UTC
Labels: bug
