### ISSUE TITLE
Terraform plan issues with 0.6.4 version

### ISSUE THREAD

**Issue by krstosavic** [charleszipp/azure-pipelines-tasks-terraform#186] opened 2021-01-11 11:24 UTC
With new 0.6.4 -var-file switch is adding "\" before file location, causing terraform plan to fail.

![image](https://user-images.githubusercontent.com/28590144/104176510-a5e9cf80-5407-11eb-9b26-e9fc88ade6f0.png)

**Comment by neallclark** [comment] 2021-01-11 12:09
Same for me, it looks like the -var-file option is wrapped in "" now, whilst the previous version did not.

**Comment by charleszipp** [comment] 2021-01-11 14:23
Related #185

**Comment by charleszipp** [comment] 2021-01-11 15:21
@neallclark and @krstosavic are you specifying your vars file in the `commandOptions` directly or using the `secureVarsFile` input?

**Comment by neallclark** [comment] 2021-01-11 15:28
Thanks for picking this up! It's much appreciated.  Yes for me I've got `-var-file"secrets.config"` in the commandOptions field.

**Comment by charleszipp** [comment] 2021-01-11 15:39
Thanks @neallclark. This should be fixed with #185. Its the same root cause I believe.

**Closed** 2021-01-11 17:35 UTC
Labels: bug

**Comment by charleszipp** [comment] 2021-01-11 18:42
fix has been published to marketplace with 0.6.5

**Comment by krstosavic** [comment] 2021-01-12 08:46
It works :)
Thanks a lot for a prompt response.
