### ISSUE TITLE
Terraform init error: No connection string, account key or sas token found, we will query account keys for your storage account

### ISSUE THREAD

**Issue by jeanpaulsmit** [charleszipp/azure-pipelines-tasks-terraform#106] opened 2020-02-18 09:26 UTC
Hi Charles, thanks for your great work, but since today I get this error:
**No connection string, account key or sas token found, we will query account keys for your storage account**

It happens on this command:
C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" storage container create --name my-tfstate --account-name mytfsa"

Full error:
2020-02-18T08:56:22.8225811Z WARNING: No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.
2020-02-18T08:56:22.8379902Z ##[error]Error: WARNING: No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.

This can also be due to some Azure CLI update.

I have enabled 'continue on error' but that is not acknowledged and I'm confused by the message it's a 'WARNING' but is thrown like an 'Error'?

**Comment by carlwoodhouse** [comment] 2020-02-18 09:59
+1 Getting this also since yesterday

**Comment by jeanpaulsmit** [comment] 2020-02-18 10:02
Might be related to this: https://github.com/Azure/azure-cli/issues/12193

**Comment by jeanpaulsmit** [comment] 2020-02-18 12:47
I've managed to work around it by using the windows-2019 build agent instead.

**Comment by carlwoodhouse** [comment] 2020-02-18 12:58
Good to know

**Comment by honeykatrina** [comment] 2020-02-18 13:39
> I've managed to work around it by using the windows-2019 build agent instead.

You saved my day and mood! It works also for me.

**Comment by charleszipp** [comment] 2020-02-18 13:51
Thanks for reporting this and the suggested workaround @jeanpaulsmit. The work around makes sense as sometimes the different hosted agent SKU's have different versions of tools such as azure cli installed. I will look into this to see if potentially one of the commands issued during the backend creation needs to be changed to accomodate newer versions of the cli. Maybe we can adjust so it doesnt emit the warning for the older versions.

Marking as a defect for now until I can prove otherwise.

**Comment by charleszipp** [comment] 2020-02-18 13:56
cc'ing @rguthriemsft, @TsuyoshiUshio, @HadwaAbdelhalem, you may encounter this on your new pipelines. See workaround above.

**Comment by charleszipp** [comment] 2020-02-18 16:16
Notes from initial investigation... It looks like what the cli might be doing to cause the task to fail is that its writing this warning to stderr. However, it may still be returning exit code zero. The task right now assumes if anything is written to stderr then the step failed. We could adjust this to require non-zero exit code to fail rather than only stderr content.

**Comment by charleszipp** [comment] 2020-02-19 19:40
Confirmed that when the warnings are emitted, that they are written to stderr. The exit code however is still zero. Trying to upload screenshot but, for some reason github is throwing an error when i attempt to do this. Was able to repro on latest azure cli 2.1.0

**Comment by charleszipp** [comment] 2020-02-19 19:47
I am working on two changes to address this issue.

First, as suggested above and in light of the data I was able to collect (see screenshot above), I am going to adjust the az-runner to only throw if stderr is defined and the exit code is **NOT** zero. This should cause the task to succeed even when this warning is thrown. This logic was also causing the task to fail on another warning related to the storage type in #91 & #86.

Second, I am going to test adding `--auth-mode login` to the container create command. I want to ensure this is compatible with all hosted agents. Assuming compatibility with older azcli versions then this will be defined explicitly in the command. That should resolve the warning.

**Comment by charleszipp** [comment] 2020-02-19 22:15
Fixed with 0.4.20 & 0.4.21 release

**Closed by charleszipp** 2020-02-19 22:15 UTC
Labels: bug
