### ISSUE TITLE
[Azure DevOps]TypeError: (0 , webapi_1.getFederatedToken) is not a function

### ISSUE THREAD

**Issue by patrickmcgannon** [charleszipp/azure-pipelines-tasks-terraform#455] opened 2024-11-22 23:42 UTC
**Describe the bug**
With our Azure DevOps task auto-upgrading from **`1.1.2` to `1.2.2`**, we are now seeing an issue on `terraform init` calls (although it could be more than just that, but that is the first usage of it).  

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)

```
      - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@1.1.2
        displayName: 'Terraform Init - ${{ dir }}'
        inputs:
          command: init
          workingDirectory: '$(Build.ArtifactStagingDirectory)/Artifacts/Terraform/${{ dir }}'
          backendType: self-configured
          commandOptions: '-backend=false'
```          

2. Execute pipeline
3. See error

```
##[error]TypeError: (0 , webapi_1.getFederatedToken) is not a function
```

**Expected behavior**
This is a regression from the working behavior in 1.1.2 for Azure.

**Screenshots**

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: Ubuntu - 22.04.5
 - Hosted
 - Terraform version used: 1.9.4
 - AzureCLI version used: 2.248.1

**Comment by WilliamBerryiii** [comment] 2024-11-23 01:49
Running into the same issue, except using Terraform 1.9.8.

**Comment by DenisBalan** [comment] 2024-11-23 06:31
Same issue here, affecting globally seems to be
Friday (yesterday)
```
Starting: Terraform Init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 1.1.2
Author       : Charles Zipp
Help         : 
==============================================================================
//successful run
```
Saturday today (all pipelines failing)

```
Starting: Terraform Init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 1.2.2
Author       : Charles Zipp
Help         : 
==============================================================================
##[error]TypeError: (0 , webapi_1.getFederatedToken) is not a function
##[error]TypeError: (0 , webapi_1.getFederatedToken) is not a function
Finishing: Terraform Init
```

**Comment by mrkenenglish** [comment] 2024-11-23 06:47
We're seeing the same issue in our org.

Our temporary fix was to pin the version, by setting ***@***.***`
instead of ***@***.***` in our pipelines.

**Comment by mrkenenglish** [comment] 2024-11-23 06:50
Hah, you daft autocorrect, that wasn't an email address you censored!

setting `TerraformCLI<at>1.1.2` instead of `TerraformCLI<at>1` in our
pipelines

**Comment by jason-johnson** [comment] 2024-11-23 07:39
Can you check again?  I had this briefly but I pushed some fixes that I had forgotten and now everything runs in my tests.

**Comment by DenisBalan** [comment] 2024-11-23 08:10
@jason-johnson no changes, same error re `##[error]TypeError: (0 , webapi_1.getFederatedToken) is not a function`

**Comment by jason-johnson** [comment] 2024-11-23 08:20
Ok, I see the issue: my tests run with `@2` which is always the latest of everything.  For the other extension versions I currently have to specify explicitly which version to use and `@1` was still pointing to an older version.  A correction is running now.

**Comment by jason-johnson** [comment] 2024-11-23 09:55
Ok, can you try it now? @DenisBalan

**Comment by jason-johnson** [comment] 2024-11-23 10:25
@WilliamBerryiii @mrkenenglish @patrickmcgannon Can someone check if it's fixed now?  It looks correct to me now.

**Comment by DenisBalan** [comment] 2024-11-23 17:02
@jason-johnson now a different error is shown :|

for a debian based container agent, running in kubernetes

```
2024-11-23T17:02:01.1662449Z ##[section]Starting: Terraform Init
2024-11-23T17:02:01.1666651Z ==============================================================================
2024-11-23T17:02:01.1666875Z Task         : Terraform CLI
2024-11-23T17:02:01.1666926Z Description  : Execute terraform cli commands
2024-11-23T17:02:01.1666997Z Version      : 1.2.3
2024-11-23T17:02:01.1667044Z Author       : Charles Zipp
2024-11-23T17:02:01.1667093Z Help         : 
2024-11-23T17:02:01.1667143Z ==============================================================================
2024-11-23T17:02:01.1687288Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2024-11-23T17:02:01.1694705Z ##[section]Finishing: Terraform Init

```

**Comment by jason-johnson** [comment] 2024-11-23 18:07
Ok, no idea.  I only test on linux and there were no errors.

**Comment by jason-johnson** [comment] 2024-11-23 18:09
In any case, the issue above was because the 1.1.1 version got redeployed instead of 1.2.2.  Closing

**Closed as completed by jason-johnson** 2024-11-23 18:09 UTC
Labels: bug

**Comment by WilliamBerryiii** [comment] 2024-11-24 00:06
@jason-johnson - I can confirm that ephemeral agents work again.  (My self-hosted however are still busted ... but that a Monday me problem 🤣). Thanks for the quick unblock!

**Comment by AMoghrabi** [comment] 2024-11-24 19:19
> @jason-johnson now a different error is shown :|
> 
> for a debian based container agent, running in kubernetes
> 
> ```
> 2024-11-23T17:02:01.1662449Z ##[section]Starting: Terraform Init
> 2024-11-23T17:02:01.1666651Z ==============================================================================
> 2024-11-23T17:02:01.1666875Z Task         : Terraform CLI
> 2024-11-23T17:02:01.1666926Z Description  : Execute terraform cli commands
> 2024-11-23T17:02:01.1666997Z Version      : 1.2.3
> 2024-11-23T17:02:01.1667044Z Author       : Charles Zipp
> 2024-11-23T17:02:01.1667093Z Help         : 
> 2024-11-23T17:02:01.1667143Z ==============================================================================
> 2024-11-23T17:02:01.1687288Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
> 2024-11-23T17:02:01.1694705Z ##[section]Finishing: Terraform Init
> ```

@jason-johnson - I'm seeing this exact same issue and Denis _is_ running this on Linux. We are seeing this on RHEL. Did you test version 1.2.3?

**Comment by jason-johnson** [comment] 2024-11-25 09:24
1.2.3 is the published/tested version.  The tag is 1.2.2 but since it has run twice, Gitversion bumps it.  Do you get the same if you try `@2`?  That would be the head of main and is always tested the most thoroughly.

**Comment by jason-johnson** [comment] 2024-11-25 09:47
Ok, I just made a branch to test the `@1` version explicitly and it does not have this issue.  I think this has to be something on the agent side.

**Comment by jason-johnson** [comment] 2024-11-25 10:14
I just went through a comparison of 1.1.1 (presumably the version which was working on your side) and literally the only difference which could have an impact was changing from `Node 10` to `Node 20.1`.  @DenisBalan @AMoghrabi can you verify that you have `Node 20.1` installed on your agents?

**Comment by DenisBalan** [comment] 2024-11-25 10:30
our agents have `NODE_MAJOR 21`
@jason-johnson please reopen the issue, as other teams in our org are also having exact same problem
```
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
```
for now the fix is just to go back for last working version.
![image](https://github.com/user-attachments/assets/289a8037-2366-4aa9-8708-106cf63b832a)

**Comment by jason-johnson** [comment] 2024-11-25 10:40
Oh that's bizarre syntax... The way these extensions work is it's basically a zip file with a structure like:

```
task.json
<task>\v0\<code>
<task>\v1\<code>
<task>\v2\<code>
```

And `taks.json` will point to the path of the task (i.e. "\<task>" above).  It takes the number at the end for the single digit version.  So I'm not sure what `@1.1.2` can be referring to.  I'm glad you've found a workaround but it seems your agent works very different than the regular ones.

EDIT: make description more accurate

**Comment by jason-johnson** [comment] 2024-11-25 12:26
@DenisBalan @AMoghrabi What base image do you use for the ADO agents you're running in Kubernetes?

**Comment by jason-johnson** [comment] 2024-11-25 16:04
It looks like it is indeed related to the agent:  #458
