### ISSUE TITLE
compatibility issue with the error Terraform command 'apply' failed with exit code '1'.:  "features": required field is not set

### ISSUE THREAD

**Issue by LayMui-Toh** [charleszipp/azure-pipelines-tasks-terraform#153] opened 2020-07-23 13:00 UTC
2020-07-23T12:51:36.2310705Z ##[section]Starting: TerraformCLI
2020-07-23T12:51:36.2326179Z ==============================================================================
2020-07-23T12:51:36.2326884Z Task         : Terraform CLI
2020-07-23T12:51:36.2327390Z Description  : Execute terraform cli commands
2020-07-23T12:51:36.2327862Z Version      : 0.5.12
2020-07-23T12:51:36.2328289Z Author       : Charles Zipp
2020-07-23T12:51:36.2328722Z Help         : 
2020-07-23T12:51:36.2329203Z ==============================================================================
2020-07-23T12:51:36.6642164Z [command]/usr/local/bin/terraform version
2020-07-23T12:51:36.8097179Z Terraform v0.12.28
2020-07-23T12:51:37.2629067Z + provider.azurerm v2.19.0
2020-07-23T12:51:37.2717099Z 
2020-07-23T12:51:37.2718338Z Your version of Terraform is out of date! The latest version
2020-07-23T12:51:37.2718952Z is 0.12.29. You can update by downloading from https://www.terraform.io/downloads.html
2020-07-23T12:51:37.2719342Z 
2020-07-23T12:51:37.2805287Z [command]/usr/local/bin/terraform apply -auto-approve -var client_id=b97db906-47b3-482d-ae33-4548ad271049 -var client_secret=*** -var ssh_public_key=/home/vsts/work/_temp/id_rsa.pub
2020-07-23T12:51:38.2433173Z Acquiring state lock. This may take a few moments...
2020-07-23T12:51:40.5784527Z [31m
2020-07-23T12:51:40.5786700Z [1m[31mError: [0m[0m[1m"features": required field is not set[0m
2020-07-23T12:51:40.5787452Z 
2020-07-23T12:51:40.5788256Z [0m[0m[0m
2020-07-23T12:51:40.9786659Z Releasing state lock. This may take a few moments...
2020-07-23T12:51:41.3595343Z 
2020-07-23T12:51:41.3722968Z ##[error]Terraform command 'apply' failed with exit code '1'.:  "features": required field is not set
2020-07-23T12:51:42.1958888Z ##[section]Finishing: TerraformCLI

**Comment by scott-doyland-burrows** [comment] 2020-07-23 13:03
In the later azure provider you need a features block, it can be left empty, like this:

provider "azurerm" {
  features {}
}

Do you have that set in the .tf file?

Scott

**Comment by LayMui** [comment] 2020-07-23 13:27
Yes I did
provider "azurerm" {
  version = "~> 1.42"
  features {}
  client_id       = var.client_id   # ENVIRONMENT VARIABLE
  client_secret   = var.client_secret # ENVIRONMENT VARIABLE
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

I still get that error

**Comment by scott-doyland-burrows** [comment] 2020-07-23 13:57
Silly question - but is that definitely the code you are using.  You have in the code:
version = "~> 1.42"
But it is picking up 2.19.

If I use 2.19 and then re-set my code to 1.42 - it installs 1.44 (which must be the oldest supported - and doesn't use 2.19).

Scott

**Comment by LayMui** [comment] 2020-07-24 02:39
Thanks, it's resolved. my bad, the issue is I point to the wrong directory in my azure-pipeline.yml
 workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/backend'

this is the folder that contain the .tf file with the provider block
please close this as not an issue. sorry about that

**Comment by scott-doyland-burrows** [comment] 2020-07-24 07:56
Good. Glad you spotted it.

**Comment by charleszipp** [comment] 2021-04-02 15:23
closing as it seems the author was able to resolve their issue. Thanks for helping out with this @scott-doyland-burrows!

**Closed by charleszipp** 2021-04-02 15:23 UTC
Labels: question, terraform-cli-task
