### ISSUE TITLE
Terraform only supports service principal authorization for azure

### ISSUE THREAD

**Issue by rhysduck** [charleszipp/azure-pipelines-tasks-terraform#393] opened 2023-11-07 14:51 UTC
**Describe the bug**
Issue when deploying infrastructure after latest update to DevOps extension

##[error]Terraform only supports service principal authorization for azure

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)

![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/102522138/6f606920-1a1a-44ef-bc9c-dd7b95c6e4c7)

3. Execute pipeline

![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/102522138/e769a379-a755-4644-a9e6-11d7d5a6db9c)

5. See error

**Expected behavior**
I expect the pipeline to run the plan as it did prior to the extension update. 

**Screenshots**
Pipeline that ran an hour before the update: 

![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/102522138/69b81649-1861-4dd1-bf29-619b1c3b4c5c)

Pipeline running yesterday with same code: 

![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/102522138/5327f2ce-8e71-4508-9d91-d53c3311bb25)

**Pipeline Logs**
2023-11-07T13:54:46.8443837Z ##[section]Starting: Terraform Plan
2023-11-07T13:54:46.8601370Z ==============================================================================
2023-11-07T13:54:46.8601801Z Task         : Terraform CLI
2023-11-07T13:54:46.8601992Z Description  : Execute terraform cli commands
2023-11-07T13:54:46.8602288Z Version      : 1.0.6
2023-11-07T13:54:46.8602415Z Author       : Charles Zipp
2023-11-07T13:54:46.8603728Z Help         : 
2023-11-07T13:54:46.8603846Z ==============================================================================
2023-11-07T13:54:52.6570851Z [command]C:\terraform\terraform_1.6.2_windows_amd64\terraform.exe version
2023-11-07T13:54:52.7887701Z Terraform v1.6.2
2023-11-07T13:54:52.7888500Z on windows_amd64
2023-11-07T13:54:52.7889138Z + provider registry.terraform.io/databricks/databricks v1.13.0
2023-11-07T13:54:52.7889960Z + provider registry.terraform.io/hashicorp/azuread v2.6.0
2023-11-07T13:54:52.7890694Z + provider registry.terraform.io/hashicorp/azurerm v3.59.0
2023-11-07T13:54:52.7891538Z + provider registry.terraform.io/hashicorp/null v2.1.2
2023-11-07T13:54:52.7892245Z + provider registry.terraform.io/hashicorp/random v2.3.1
2023-11-07T13:54:52.7893200Z + provider registry.terraform.io/hashicorp/template v2.2.0
2023-11-07T13:54:52.7927106Z + provider registry.terraform.io/hashicorp/tls v2.2.0
2023-11-07T13:54:52.7930475Z 
2023-11-07T13:54:52.7931212Z Your version of Terraform is out of date! The latest version
2023-11-07T13:54:52.7932205Z is 1.6.3. You can update by downloading from https://www.terraform.io/downloads.html
2023-11-07T13:54:52.8084607Z ##[error]Terraform only supports service principal authorization for azure
2023-11-07T13:54:52.8241157Z ##[error]Terraform only supports service principal authorization for azure
2023-11-07T13:54:53.0755214Z ##[section]Finishing: Terraform Plan

**Agent Configuration**
 - OS: Windows server
 - Self Hosted
 - Terraform version used v1.6.2
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**

**Comment by mroussel** [comment] 2023-11-07 16:01
Same problem here.

**Comment by Marquis79** [comment] 2023-11-07 16:07
Same problem here.

**Comment by jason-johnson** [comment] 2023-11-07 16:52
Duplicate of #388

**Comment by jason-johnson** [comment] 2023-11-07 16:55
Oh, sorry.  Read it too fast.  This is bizarre.  All the new update does is add versions to the task.  Can you try with TerraformCli@0 and  TerraformCli@2?

**Comment by rhysduck** [comment] 2023-11-07 17:02
Hey Jason,  TerraformCli@2 is working for the moment thanks.

**Comment by jason-johnson** [comment] 2023-11-07 17:12
Just keep in mind that TerraformCli@2 is not the stable one.  Later releases can break this without warning.  On a good note, though, what is in TerraformCli@2 right now should be in TerraformCli@1 on the next release.

**Comment by jaredfholgate** [comment] 2023-11-07 20:24
@jason-johnson It looks like an old version has been deployed to 1.0.6 somehow. That error message `Terraform only supports service principal authorization for azure` only existed in the code prior to me adding WIF and MI support. And same for the init message of `Terraform backend initialization for AzureRM only support service principal authorization`. Both were removed in that PR: https://github.com/jason-johnson/azure-pipelines-tasks-terraform/pull/359/files

See here:

- https://github.com/jason-johnson/azure-pipelines-tasks-terraform/pull/359/files#diff-04201ffd902436222e97a7b1c004b9f923829c7ea5f4aa636081b2793ce22535
- https://github.com/jason-johnson/azure-pipelines-tasks-terraform/pull/359/files#diff-475aba688b15cb390cefa49400819e64fde03be96a67322ba6053ca5349de2c8

**Comment by jaredfholgate** [comment] 2023-11-07 20:39
@rhysduck Unrelated to the error, but I see you are supplying env vars for `azurerm` config as well as a service connection. The task will overwrite those env vars if I am not mistaken, so wondering what you are trying to achieve by supplying them? If you need to supply via env vars instead of the recommended service connection method, there is no need to use the task, you can just run the cli directly instead.

**Comment by lynkz-matt-psaltis** [comment] 2023-11-08 07:12
> Hey Jason, TerraformCli@2 is working for the moment thanks.

Same here, last successful build was Monday, moved to @2 and starts working again.

**Comment by jason-johnson** [comment] 2023-11-08 17:53
Ok, this should be fixed by #396 now.  Please feel free to reopen if you have any further issues with it.

**Closed as completed by jason-johnson** 2023-11-08 17:53 UTC
Labels: bug
