### ISSUE TITLE
az cli authentication with service principal fails if Client Secret begins with a dash

### ISSUE THREAD

**Issue by timothycrall** [charleszipp/azure-pipelines-tasks-terraform#391] opened 2023-11-02 19:36 UTC
**Describe the bug**
When authenticating with a service principal, the az login fails if the Client Secret begins with a dash.

```
/usr/bin/az login --service-principal -t xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -u *** -p ***
ERROR: argument --password/-p: expected one argument

Examples from AI knowledge base:
az login --service-principal -u http://azure-cli-2016-08-05-14-31-15/ -p VerySecret --tenant contoso.onmicrosoft.com
Log in with a service principal using client secret. Use -p=secret if the first character of the password is '-'.
```

As noted by the error message, the solution is to us the `-p=secret` syntax on the `az login` command.  The AzureCLI@ task used to have this same bug but it eventually got fixed there.

**To Reproduce**
Client Secrets are randomly generated strings using the characters a-z, 0-9, dash, underline, dot, and tilde.  Therefore there's a 1/40 chance that any given client string starts with a dash, making intentional recreation difficult.  But because the source of the error is clear and the solution well established, it should be easy enough to fix regardless.  I suppose it could be recreated using a stand user and setting the password to something starting with a dash.

**Expected behavior**
az login works correctly even when the password/secret begins with a dash.

**Comment by timothycrall** [comment] 2023-11-02 20:04
References:
https://github.com/Azure/azure-cli/issues/12105
https://github.com/microsoft/azure-pipelines-tasks/issues/12908

**Comment by jason-johnson** [comment] 2023-11-03 13:42
Duplicate of #284.  There is a PR for it in flight; #373

**Closed as completed by jason-johnson** 2023-11-03 13:42 UTC
Labels: duplicate
