### ISSUE TITLE
Run init and plan using different service connection

### ISSUE THREAD

**Issue by luanbon** [charleszipp/azure-pipelines-tasks-terraform#78] opened 2019-08-07 21:37 UTC
I have my backend configured and initialized using a service connection (service principal), and then I need to run the plan in another environment with another service principal, but this tasks fails because it is trying access the environment variables from the previous step, causing an error when applying changes. I realize that the plan task is using the "ARN _..." variables from the backend initialization task.

**YAML Pipeline**

```yaml
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
    - terraform/multi-region/*
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformCLI@0
    displayName: Terraform Init Backend
    continueOnError: false
    inputs:
      command: 'init'
      workingDirectory: './terraform/single-region'
      backendType: 'azurerm'
      backendServiceArm: 'Terraform Service Principal - Production'
      backendAzureRmResourceGroupName: 'x'
      backendAzureRmStorageAccountName: 'y'
      backendAzureRmContainerName: 'z'
      backendAzureRmKey: 'consul.tfstate'
  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      workingDirectory: './terraform/single-region'
      environmentServiceName: 'Terraform Service Principal - Development'
      commandOptions: '-input=false -detailed-exitcode -out=tfplan'
  - task: CopyFiles@2
    condition: eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true')
    displayName: Copy Source Files
    inputs:
      contents: '$(Build.SourcesDirectory)/**'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    condition: eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true')
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
```

**Error**

Error loading state: Error retrieving keys for Storage Account "x": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="y" Message="Resource group 'z' could not be found."

**Comment by charleszipp** [comment] 2019-08-08 18:21
@luanbon The environment variables for the azurerm provider are set with each task. I believe the reason why it may look like they are being reused from init is because terraform writes these to disk in the working directory. You will notice this if you run it locally on your machine. This file, when run on the agent, is placed in a temp directory that is deleted after the pipeline finishes. 

I suspect for this to work, a code change in the task will have to be made to force terraform to take the new values for these env values instead of using whats written to the state file.

**Comment by charleszipp** [comment] 2021-03-09 14:56
Potential duplicate of #141

**Comment by charleszipp** [comment] 2021-03-30 20:14
See comment from #141. Believe this applies to this issue as well

> I have dug into this more @rhollins. I do not think this is a defect as this behavior (of having to provide the access key or rbac to the backend) is required even when using terraform natively (i.e. independent of this task). So this behavior is expected. You can search the error returned in this case and you will see multiple posts claiming this along with supporting docs.
However, in my testing, it appears we could make this easier with an enhancement. If the access key is provided at the time of running terraform init, it does NOT need to be provided in subsequent commands (i.e. plan/apply). It will be stored in the local terraform.tfstate file and reused.
My thought is if we added an option to control the auth mechanism, then we could have the this extension lookup the access key and provide it as backend-config when it runs terraform init. That would allow subsequent commands to run under a different service principal and while enabling access to a backend in a separate sub (via access key). We would need to considerate of the security implications however of handling access keys and making sure they dont appear in build logs or other unsecured areas. This is why i dont like the idea of just doing this by default.
For all these reasons, I would like to replace this with an enhancement request to enable/automate access key auth to azurerm backend. Let me know your thoughts @rhollins

**Comment by charleszipp** [comment] 2021-03-30 20:37
closing in favor of #257

**Closed by charleszipp** 2021-03-30 20:37 UTC
Labels: bug, duplicate, sev2, terraform-cli-task
