### ISSUE TITLE
The default kind for created storage account will change to 'StorageV2' from 'Storage' in future

### ISSUE THREAD

**Issue by jeanpaulsmit** [charleszipp/azure-pipelines-tasks-terraform#86] opened 2019-10-04 09:23 UTC
It seems the functionality to automatically create an azurerm Backend on init doesn't work anymore.
I selected the option to 'Create Backend (if not exists)' and then this error showed up:
##[error]Error: WARNING: The default kind for created storage account will change to 'StorageV2' from 'Storage' in future

Although the task created the storage account, I need to enable 'continue on error' to make it work. It would be nice if the ARM template behind it would be updated.

**Comment by KellyGriffin** [comment] 2019-10-26 00:20
Confirmed - I get the same issue.  Only away around it so far is to re-run the project and it works if there is an existing storage account.  Mine keeps failing on first runs.

**Comment by KellyGriffin** [comment] 2019-10-26 00:26
All that needs to occur is change the az-storage-account-create.ts file

In the lable "kind" - it needs to change from BlobStorage to StorageV2 - that will fix it.

**Comment by charleszipp** [comment] 2019-10-26 11:34
Thanks @KellyGriffin for submitting the fix for this issue with #89. Your change should be pushed to the marketplace as 0.4.15 today. Im just waiting on CI from master to finish up

**Comment by KellyGriffin** [comment] 2019-10-26 11:42
@charleszipp you're very welcome.

**Comment by KellyGriffin** [comment] 2019-10-27 05:34
When will the Azure Marketplace be updated?  It's still showing as 4.13?

**Comment by charleszipp** [comment] 2019-10-27 12:50
There was an error thrown from the marketplace yesterday when i attempted to publish. All I got was "something went wrong, please try again later" from the log. Unfortunately i cant simply republish because it wants the version to be incremented. Therefore, im going to have to bump the version somehow and retry. It may be monday before i can get this resolved

**Comment by charleszipp** [comment] 2019-10-27 18:54
@KellyGriffin i was able to bump the version and retry publish to the marketplace. This time it worked. So the change is available with 0.4.15

**Closed** 2019-10-27 18:55 UTC
Labels: bug, good first issue, help wanted

**Comment by KellyGriffin** [comment] 2019-10-27 22:07
Awesome - thank you...That worked a treat :)

**Comment by jeanpaulsmit** [comment] 2019-10-28 07:44
Thanks @KellyGriffin and @charleszipp for fixing this!
