### ISSUE TITLE
The version 0.4.15 of the task still is broken when the backend is needed

### ISSUE THREAD

**Issue by JorTurFer** [charleszipp/azure-pipelines-tasks-terraform#91] opened 2019-10-31 10:47 UTC
After the issue #86 , the problem should be fixed. When I use it without previous backend, the task still display the message:
_Error: WARNING: The default kind for created storage account will change to 'StorageV2' from 'Storage' in future_
![image](https://user-images.githubusercontent.com/36899226/67940333-b1225800-fbd3-11e9-8f29-b8e7672100c4.png)
The version is 0.4.15:
![image](https://user-images.githubusercontent.com/36899226/67940361-bed7dd80-fbd3-11e9-9186-c4779e99b0d9.png)

The storage is created correctly but the task fails. In the next tries the task works correctly becouse the storeage was created previously

**Comment by jeanpaulsmit** [comment] 2019-11-05 10:53
I can confirm this still (or again?) seems to be an issue, on the mentioned version.
@charleszipp any idea?

**Comment by mabbotts9797** [comment] 2019-11-13 08:19
@charleszipp this does still seem to be an issue on V0.4.15. The storage account is created but the task fails.

**Comment by jeanpaulsmit** [comment] 2019-12-19 14:31
@mabbotts9797 @charleszipp this doesn't seem to be an issue on the task, rather an issue on the DevOps agents.
It's related to the Azure CLI version. 
Locally I run CLI version 2.0.52 and it appears to work up to version 2.0.72.
However when Microsoft updated to version 2.0.73 it became an issue on the build agent:
https://developercommunity.visualstudio.com/content/problem/752118/az-cli-reports-warnings-that-breaks-releases.html

So I guess this can't be fixed by Charles (although he's working for Microsoft ;-) )

**Comment by charleszipp** [comment] 2020-02-19 19:49
FYI, this should be resolved with #107. The azure-cli writes warnings to stderr. The terraformcli extension interprets the existence of content on stderr as failures and doesnt factor the exit code into that decision. That PR will factor in the exit code.

**Comment by charleszipp** [comment] 2020-02-19 22:18
I am no longer able to reproduce this issue. Also, as of version 0.4.20, warnings from the azure cli will no longer cause the task to fail. Closing this issue.

**Closed by charleszipp** 2020-02-19 22:18 UTC
