### ISSUE TITLE
How to authenticate using Service Principal and certificate in the terraform task in azure pipelines.

### ISSUE THREAD

**Issue by sudhir-ops** [charleszipp/azure-pipelines-tasks-terraform#401] opened 2023-11-24 01:08 UTC
**Describe the bug**
Is it possible to authenticate via service principal and certificate in terraform task? So far, I'm seeing only service connection is available for authentication.

By the method provided in below link, is it possible to input values in to terraform task and authenticate?

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate

**Comment by jason-johnson** [comment] 2024-02-02 19:16
Duplicate of #270

**Closed as completed by jason-johnson** 2024-02-02 19:16 UTC
Labels: bug
