### ISSUE TITLE
Error message "Input required: backendAzureRmResourceGroupLocation"

### ISSUE THREAD

**Issue by doanduyhai** [charleszipp/azure-pipelines-tasks-terraform#234] opened 2021-12-29 16:47 UTC
**Describe the bug**
After the last commit https://github.com/charleszipp/azure-pipelines-tasks-terraform/commit/2b15a9d0f760d554670682be1b8a6a5edaaac3a4

We start to have issued with the Terraform Init step in our release pipeline with the following error message

```
2021-12-29T16:31:40.1576361Z Terraform has been successfully initialized!
2021-12-29T16:31:40.1685323Z ##[error]Error: Input required: backendAzureRmResourceGroupLocation
```

BEFORE this commit, this was working fine

**To Reproduce**
1. Setup a basic pipeline with a Terraform Init step, using an AzureRM backend and pointing to a storage account in Azure
2. Execute pipeline
3. See error in the logs

```
2021-12-29T16:31:40.1685323Z ##[error]Error: Input required: backendAzureRmResourceGroupLocation
````

**Expected behavior**
There should be no issue

**Screenshots**

**Pipeline Logs**

```
2021-12-29T16:31:35.1432587Z ##[section]Starting: Terraform Init
2021-12-29T16:31:35.1443492Z ==============================================================================
2021-12-29T16:31:35.1443824Z Task         : Terraform CLI
2021-12-29T16:31:35.1444095Z Description  : Execute terraform cli commands
2021-12-29T16:31:35.1444324Z Version      : 0.7.0
2021-12-29T16:31:35.1457142Z Author       : Charles Zipp
2021-12-29T16:31:35.1457676Z Help         : 
2021-12-29T16:31:35.1458019Z ==============================================================================
2021-12-29T16:31:35.5234118Z [command]/agent/_work/_tool/terraform/1.1.0/x64/terraform version
2021-12-29T16:31:35.5632725Z Terraform v1.1.0
2021-12-29T16:31:35.5633146Z on linux_amd64
2021-12-29T16:31:35.5633711Z + provider registry.terraform.io/hashicorp/azurerm v2.88.1
2021-12-29T16:31:35.5633910Z 
2021-12-29T16:31:35.5634221Z Your version of Terraform is out of date! The latest version
2021-12-29T16:31:35.5634682Z is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
2021-12-29T16:31:35.5849728Z [command]/agent/_work/_tool/terraform/1.1.0/x64/terraform init -backend-config=storage_account_name=xxx -backend-config=container_name=xxx -backend-config=key=xxx.tfstate -backend-config=resource_group_name=xxx -backend-config=subscription_id=xxx -backend-config=tenant_id=*** -backend-config=client_id=*** -backend-config=client_secret=*** -no-color
2021-12-29T16:31:35.6242246Z Initializing modules...
2021-12-29T16:31:35.6321220Z - naming_convention in ../../00_naming_convention
2021-12-29T16:31:35.6328249Z - network_plan in ../../00_network_plan
2021-12-29T16:31:35.6437120Z 
2021-12-29T16:31:35.6437583Z Initializing the backend...
2021-12-29T16:31:36.0828597Z 
2021-12-29T16:31:36.0829452Z Successfully configured the backend "azurerm"! Terraform will automatically
2021-12-29T16:31:36.0829884Z use this backend unless the backend configuration changes.
2021-12-29T16:31:36.1919646Z 
2021-12-29T16:31:36.1920586Z Initializing provider plugins...
2021-12-29T16:31:36.1922220Z - Reusing previous version of hashicorp/azurerm from the dependency lock file
2021-12-29T16:31:36.2620544Z - Installing hashicorp/azurerm v2.88.1...
2021-12-29T16:31:40.1575656Z - Installed hashicorp/azurerm v2.88.1 (signed by HashiCorp)
2021-12-29T16:31:40.1576007Z 
2021-12-29T16:31:40.1576361Z Terraform has been successfully initialized!
2021-12-29T16:31:40.1685323Z ##[error]Error: Input required: backendAzureRmResourceGroupLocation
2021-12-29T16:31:40.1707398Z ##[section]Finishing: Terraform Init

```

**Agent Configuration**
 - OS: Ubunbu LTS 20.x
 - Self Hosted
 - Terraform version used = **1.1.0**
 - AzureCLI version used = **2.31.0**

**Additional context**

**Comment by pavelpikatamcs** [comment] 2021-12-29 16:49
You beat my be 1 minute :D #235

**Comment by charleszipp** [comment] 2021-12-29 16:52
closing this as duplicate of #235

**Closed as completed by charleszipp** 2021-12-29 16:52 UTC
Labels: bug, sev2
