### ISSUE TITLE
Error running init with new version of 0.15.0

### ISSUE THREAD

**Issue by yellrollo** [charleszipp/azure-pipelines-tasks-terraform#268] opened 2021-04-15 07:29 UTC
Hi, we've been using the latest version in our init task and after the 0.15 release yesterday, init fails with the attached errors.

It uses the azurerm backend type, it looks like it doesnt like the extra parameters are being added on in the cli.

![image](https://user-images.githubusercontent.com/78438548/114830792-82e30900-9dc4-11eb-985e-f845112055eb.png)

**Comment by timja** [comment] 2021-04-15 10:23
Duplicate of https://github.com/charleszipp/azure-pipelines-tasks-terraform/issues/123

**Comment by charleszipp** [comment] 2021-04-15 13:10
Appreciate you reporting this @yellrollo and @timja. Have bumped the priority of this and #123. As mentioned in #123, there are still users on 0.11 and prior which do not recognize the parameters needed by 0.15. That makes fixing this slightly more complex as the parameters the task uses depends on the version of terraform being used.

To fix this, the stdout from running terraform version at the start will need to be captured and stored within ITaskContext. As part of doing this it, would be helpful it that could also extract major, minor, and patch version segments and store as integers for easier comparison. Then, within terraform init, a condition will need to be added that basically executes as follows...

```javascript
// assuming terraform version stdout has been parsed as semantic version and stored within ITaskContext by this point
if(ctx.terraformVersionMinor < 12){
  //use arm_* config variables
}
else {
 //use client_id, client_secret, tenant_id, subscription_id config vars
}
```

**Comment by charleszipp** [comment] 2021-04-15 13:12
For others that may encounter this, I would suggest **not** using `latest` in terraform installer until this is resolved. Instead use the latest compatible terraform version for your pipeline prior to 0.15's release.

**Comment by Radamonas** [comment] 2021-04-15 13:59
Why not providing additional version of the task for new Terraform CLI? Ones who are still using old CLI version could use 0*, while new version could be supporting from 14.* up?

**Comment by DenWin** [comment] 2021-04-15 17:35
You could provide both versions.  "arm_teanant_id" and "tenant_id"

0.11 would not know about the latter one and ignore it
0.12 - 0.14 would give a warning, but accept both 
and 0.15 would ignore the first

Another approach would be to use Environment variables? Is this even possible? But the variable name for the ENV-Variable is unchanged since basically forever.

**Closed** 2021-04-15 20:30 UTC
Labels: bug, sev2, terraform-cli-task
