### ISSUE TITLE
Azure Pipeline Error On Initialize due to node 10 dependency.

### ISSUE THREAD

**Issue by richhoward1** [charleszipp/azure-pipelines-tasks-terraform#444] opened 2024-09-25 12:12 UTC
**Describe the bug**
As of this morning, Azure Pipelines is throwing warnings in Job Initialization step for both the TerraformInstaller@1 and TerraformCli@1.

The errors are as follows: 

##[warning]Task 'Terraform Installer' version 1 (TerraformInstaller@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

##[warning]Task 'Terraform CLI' version 1 (TerraformCLI@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**To Reproduce**
1. Setup pipeline using TerraformInstaller@1 and TerraformCli@2
2. Execute pipeline
3. See warnings in Job Initialization

**Expected behavior**
The job should initialise without throwing the warnings above

**Screenshots**
![image](https://github.com/user-attachments/assets/9f2dae8a-015e-4cc3-b76b-dbe2c78013f6)

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: ubuntu-22.04
 - Self Hosted
 - Terraform version used: N/A
 - AzureCLI version used: N/A

**Additional context**

**Comment by jason-johnson** [comment] 2024-09-26 06:39
Duplicate of #430

**Closed as completed by jason-johnson** 2024-09-26 06:39 UTC
Labels: bug
